"""Campaign dossier (Markdown) generation.

The dossier turns a finished (or in-progress) campaign into a coherent
institutional case file: status, final state, the turn-by-turn timeline, canon,
open threads, and a faction summary. It is generated deterministically from
campaign data only -- no model output, no state mutation.

This is intentionally a plain-string builder so the engine stays framework-free;
the backend can return it as text or the frontend can render / download it.
"""

from __future__ import annotations

from typing import List

from engine.models import Campaign, CampaignStatus


def _risk_label(variable: str, value: int) -> str:
    return f"{value}/100"


def render_dossier_markdown(campaign: Campaign) -> str:
    """Render the campaign as a Markdown case-file dossier."""
    lines: List[str] = []
    v = campaign.world_state.variables
    status = campaign.status

    lines.append(f"# Campaign Dossier \u2014 {campaign.name}")
    lines.append("")
    lines.append(f"- **Campaign ID:** `{campaign.id}`")
    lines.append(f"- **Scenario:** `{campaign.scenario_id}`")
    lines.append(f"- **Status:** {status}")
    lines.append(f"- **Turns resolved:** {len(campaign.turn_history)} / {campaign.max_turns}")
    if campaign.failure_reason:
        lines.append(f"- **Failure reason:** {campaign.failure_reason}")
    lines.append(f"- **Created:** {campaign.created_at or 'unknown'}")
    lines.append("")

    lines.append("## Final World State")
    lines.append("")
    lines.append("| Variable | Value |")
    lines.append("| --- | --- |")
    for key in sorted(v.keys()):
        lines.append(f"| {key} | {_risk_label(key, v[key])} |")
    lines.append("")

    # Faction summary
    lines.append("## Faction Summary")
    lines.append("")
    lines.append("| Faction | Alignment | Posture | Influence | Pressure |")
    lines.append("| --- | --- | --- | --- | --- |")
    for f in campaign.world_state.factions:
        lines.append(
            f"| {f.name} | {f.alignment} | {f.posture} | "
            f"{f.influence} | {f.current_pressure} |"
        )
    lines.append("")

    # Turn-by-turn timeline
    lines.append("## Turn-by-Turn Timeline")
    lines.append("")
    if not campaign.turn_history:
        lines.append("_No turns resolved yet._")
        lines.append("")
    else:
        for t in campaign.turn_history:
            lines.append(f"### Turn {t.turn_number} \u2014 {t.advice_label}")
            lines.append("")
            lines.append(f"- **NPC decision:** {t.decision.decision_type} "
                         f"(adherence {int(round(t.decision.adherence * 100))}%)")
            lines.append(f"- **Status after:** {t.status_after}")
            lines.append(f"- **Client:** {t.decision.decider}")
            lines.append(f"- **Aftermath:** {t.aftermath_summary}")
            if t.consequence_stack.opened_threads:
                lines.append("- **Threads opened:** "
                             + "; ".join(t.consequence_stack.opened_threads))
            lines.append("")

    # Canon
    lines.append("## Canon Archive")
    lines.append("")
    if not campaign.canon:
        lines.append("_No canon entries._")
        lines.append("")
    else:
        for c in campaign.canon:
            lines.append(f"- **[T{c.turn_number}] {c.title}** \u2014 _{c.category}_ "
                         f"({c.public_status})")
            lines.append(f"  - {c.body}")
        lines.append("")

    # Open threads
    open_only = [t for t in campaign.open_threads if t.status != "resolved"]
    lines.append("## Open Threads")
    lines.append("")
    if not open_only:
        lines.append("_No open threads._")
        lines.append("")
    else:
        for t in open_only:
            lines.append(f"- **{t.title}** (opened turn {t.turn_opened}, {t.status})")
            lines.append(f"  - {t.summary}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by the Continuity Failure deterministic engine. "
                 "AI integration is not implemented in this build._")
    lines.append("")
    return "\n".join(lines)


def dossier_filename(campaign: Campaign) -> str:
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in campaign.name.strip())
    safe = safe.strip("-") or "campaign"
    suffix = {
        CampaignStatus.ACTIVE: "active",
        CampaignStatus.COMPLETED: "completed",
        CampaignStatus.FAILED: "failed",
    }.get(campaign.status, "campaign")
    return f"{safe}-{suffix}.md"
